export enum AppEvents {
  SET_APP_DATA_NAME = 'SET_APP_DATA_NAME',
  SET_LUCIADMAP_TREE_NODE = 'SET_LUCIADMAP_TREE_NODE',
  SET_LUCIADMAP_MAP = 'SET_LUCIADMAP_MAP',
  SET_LUCIADMAP_PROJ = 'SET_LUCIADMAP_PROJ',
  SET_APP_COMMAND = 'SET_APP_COMMAND',
}
