export enum LayerTypes {
    WFSLayer = 'WFSLayer',
    WFS3Layer = 'WFS3Layer',
    WMSLayer = 'WMSLayer',
    WMTSLayer = "WMTSLayer",
    TMSLayer = 'TMSLayer',
    OGC3DTilesLayer = 'OGC3DTilesLayer',
    BingMapsLayer = 'BingMapsLayer',
    LTSLayer = 'LTSLayer',
    GeoJSONFileLayer = 'GeoJSONFileLayer',
    LayerGroup = "LayerGroup",
    GridLayer = "GridLayer",
    EditableFeatureLayer = "EditableFeatureLayer",
    Root = "root",
    FeaturesFileLayer = "FeaturesFileLayer",
}
