export enum ApplicationCommands {
    CREATELAYER = "CREATELAYER",
    REFRESHLAYERS = "REFRESHLAYERS",
    MAPSAVESTATUS = "MAPSAVESTATUS",
    MAPRESTORE = "MAPRESTORE",
    WORKSPACERESTORE = "WORKSPACERESTORE",
    WORKSPACESAVE = "WORKSPACESAVE",
    APPTOAST = "APPTOAST",
    WORKSPACENEW = "WORKSPACENEW",
    MAPRESET = "MAPRESET",
}

